"""empty message

Revision ID: 118f16b438f1
Revises: 
Create Date: 2021-06-02 12:10:35.403461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118f16b438f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('birthday', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'birthday')
    # ### end Alembic commands ###
