"""empty message

Revision ID: 5fd09bd46ee4
Revises: 118f16b438f1
Create Date: 2021-06-19 15:54:38.566985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd09bd46ee4'
down_revision = '118f16b438f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee') as batch_op:
        batch_op.alter_column('birthday', existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee') as batch_op:
        batch_op.alter_column('birthday', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
